apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/managed-by: google-cloud-deploy
    deploy.cloud.google.com/delivery-pipeline-id: git-pipeline
    deploy.cloud.google.com/location: us-west2
    deploy.cloud.google.com/project-id: minnah-testing
    deploy.cloud.google.com/release-id: release-007
    deploy.cloud.google.com/target-id: git-prod
  name: getting-started
spec:
  containers:
    - image: nginx:1.14.2
      name: nginx
      ports:
        - containerPort: 90
